# Generated by Django 5.1 on 2024-09-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
